### ISSUE TITLE
installation error: module 'templating' missing

### ISSUE THREAD

**Issue by ddyan** [nigma/pywt#12]
The following information is collected during installation using pip. Similar massage is also received while installing using git cloned file.

Collecting pywavelets
  Using cached PyWavelets-0.2.2.zip
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/private/var/folders/6z/13s_74351fvdz6zfd2np0zdm0000gn/T/pip-build-8507a3rq/pywavelets/setup.py", line 14, in <module>
        from util import commands
      File "/private/var/folders/6z/13s_74351fvdz6zfd2np0zdm0000gn/T/pip-build-8507a3rq/pywavelets/util/commands.py", line 25, in <module>
        import templating
    ImportError: No module named 'templating'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/6z/13s_74351fvdz6zfd2np0zdm0000gn/T/pip-build-8507a3rq/pywavelets

**Comment by rgommers** [comment]
Issue is resolved in master branch and upcoming v0.3.0 release of https://github.com/PyWavelets/pywt, so closing this issue.
