### ISSUE TITLE
Installation fails on Python3.4

### ISSUE THREAD

**Issue by DSLituiev** [nigma/pywt#14]
I cannot install the module. Trying from pip repositories:

```
pip3 install pywt --pre
Collecting pywt
  Could not find a version that satisfies the requirement pywt (from versions: )
No matching distribution found for pywt
```

OK. I clone it from github and run `pip3 install .`. Error:

```
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/var/folders/97/527pmsxx5nb7_vfnb8621nqm0000gn/T/pip-gfrdmja_-build/setup.py", line 14, in <module>
        from util import commands
      File "/private/var/folders/97/527pmsxx5nb7_vfnb8621nqm0000gn/T/pip-gfrdmja_-build/util/commands.py", line 25, in <module>
        import templating
    ImportError: No module named 'templating'
```

I guess it is not specified as a dependency explicitly. When I try to install `templating`, I get the same error:

```
pip3 install templating
Collecting templating
  Could not find a version that satisfies the requirement templating (from versions: )
No matching distribution found for templating
```

As i cannot find `templating` repository I post it here

**Comment by DSLituiev** [comment]
Works with `pip3 install PyWavelet`.
